//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.0.
// 
#pragma warning disable 1591

namespace CreatePNR_AutomationApp.FlightService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IConnectPoint_Flight", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransactionInfo))]
    public partial class ConnectPoint_Flight : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RetrieveSeatAvailabilityListOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetrieveAirportRoutesOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateLidAircraftOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ConnectPoint_Flight() {
            this.Url = global::CreatePNR_AutomationApp.Properties.Settings.Default.CreatePNR_AutomationApp_FlightService_ConnectPoint_Flight;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RetrieveSeatAvailabilityListCompletedEventHandler RetrieveSeatAvailabilityListCompleted;
        
        /// <remarks/>
        public event RetrieveAirportRoutesCompletedEventHandler RetrieveAirportRoutesCompleted;
        
        /// <remarks/>
        public event UpdateLidAircraftCompletedEventHandler UpdateLidAircraftCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IConnectPoint_Flight/RetrieveSeatAvailabilityList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ViewSeatAvailability RetrieveSeatAvailabilityList([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] RetrieveSeatAvailabilityList RetrieveSeatAvailabilityListRequest) {
            object[] results = this.Invoke("RetrieveSeatAvailabilityList", new object[] {
                        RetrieveSeatAvailabilityListRequest});
            return ((ViewSeatAvailability)(results[0]));
        }
        
        /// <remarks/>
        public void RetrieveSeatAvailabilityListAsync(RetrieveSeatAvailabilityList RetrieveSeatAvailabilityListRequest) {
            this.RetrieveSeatAvailabilityListAsync(RetrieveSeatAvailabilityListRequest, null);
        }
        
        /// <remarks/>
        public void RetrieveSeatAvailabilityListAsync(RetrieveSeatAvailabilityList RetrieveSeatAvailabilityListRequest, object userState) {
            if ((this.RetrieveSeatAvailabilityListOperationCompleted == null)) {
                this.RetrieveSeatAvailabilityListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetrieveSeatAvailabilityListOperationCompleted);
            }
            this.InvokeAsync("RetrieveSeatAvailabilityList", new object[] {
                        RetrieveSeatAvailabilityListRequest}, this.RetrieveSeatAvailabilityListOperationCompleted, userState);
        }
        
        private void OnRetrieveSeatAvailabilityListOperationCompleted(object arg) {
            if ((this.RetrieveSeatAvailabilityListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetrieveSeatAvailabilityListCompleted(this, new RetrieveSeatAvailabilityListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IConnectPoint_Flight/RetrieveAirportRoutes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ViewAirportRoutes RetrieveAirportRoutes([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] RetrieveAirportRoutes RetrieveAirportRoutesRequest) {
            object[] results = this.Invoke("RetrieveAirportRoutes", new object[] {
                        RetrieveAirportRoutesRequest});
            return ((ViewAirportRoutes)(results[0]));
        }
        
        /// <remarks/>
        public void RetrieveAirportRoutesAsync(RetrieveAirportRoutes RetrieveAirportRoutesRequest) {
            this.RetrieveAirportRoutesAsync(RetrieveAirportRoutesRequest, null);
        }
        
        /// <remarks/>
        public void RetrieveAirportRoutesAsync(RetrieveAirportRoutes RetrieveAirportRoutesRequest, object userState) {
            if ((this.RetrieveAirportRoutesOperationCompleted == null)) {
                this.RetrieveAirportRoutesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetrieveAirportRoutesOperationCompleted);
            }
            this.InvokeAsync("RetrieveAirportRoutes", new object[] {
                        RetrieveAirportRoutesRequest}, this.RetrieveAirportRoutesOperationCompleted, userState);
        }
        
        private void OnRetrieveAirportRoutesOperationCompleted(object arg) {
            if ((this.RetrieveAirportRoutesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetrieveAirportRoutesCompleted(this, new RetrieveAirportRoutesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IConnectPoint_Flight/UpdateLidAircraft", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ViewUpdateLidAircraftCollection UpdateLidAircraft([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] UpdateInventoryAirCraftLid UpdateLidAircraftRequest) {
            object[] results = this.Invoke("UpdateLidAircraft", new object[] {
                        UpdateLidAircraftRequest});
            return ((ViewUpdateLidAircraftCollection)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateLidAircraftAsync(UpdateInventoryAirCraftLid UpdateLidAircraftRequest) {
            this.UpdateLidAircraftAsync(UpdateLidAircraftRequest, null);
        }
        
        /// <remarks/>
        public void UpdateLidAircraftAsync(UpdateInventoryAirCraftLid UpdateLidAircraftRequest, object userState) {
            if ((this.UpdateLidAircraftOperationCompleted == null)) {
                this.UpdateLidAircraftOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateLidAircraftOperationCompleted);
            }
            this.InvokeAsync("UpdateLidAircraft", new object[] {
                        UpdateLidAircraftRequest}, this.UpdateLidAircraftOperationCompleted, userState);
        }
        
        private void OnUpdateLidAircraftOperationCompleted(object arg) {
            if ((this.UpdateLidAircraftCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateLidAircraftCompleted(this, new UpdateLidAircraftCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Radixx.ConnectPoint.Flight.Request")]
    public partial class RetrieveSeatAvailabilityList : TransactionInfo {
        
        private int logicalFlightIDField;
        
        private System.DateTime departureDateField;
        
        private string cabinNameField;
        
        private string currencyField;
        
        private long uTCOffsetField;
        
        /// <remarks/>
        public int LogicalFlightID {
            get {
                return this.logicalFlightIDField;
            }
            set {
                this.logicalFlightIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DepartureDate {
            get {
                return this.departureDateField;
            }
            set {
                this.departureDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CabinName {
            get {
                return this.cabinNameField;
            }
            set {
                this.cabinNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        public long UTCOffset {
            get {
                return this.uTCOffsetField;
            }
            set {
                this.uTCOffsetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UpdateInventoryAirCraftLid))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RetrieveAirportRoutes))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RetrieveSeatAvailabilityList))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Radixx.ConnectPoint.Request")]
    public partial class TransactionInfo {
        
        private string securityGUIDField;
        
        private CarrierCode[] carrierCodesField;
        
        private string clientIPAddressField;
        
        private string historicUserNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SecurityGUID {
            get {
                return this.securityGUIDField;
            }
            set {
                this.securityGUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public CarrierCode[] CarrierCodes {
            get {
                return this.carrierCodesField;
            }
            set {
                this.carrierCodesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ClientIPAddress {
            get {
                return this.clientIPAddressField;
            }
            set {
                this.clientIPAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string HistoricUserName {
            get {
                return this.historicUserNameField;
            }
            set {
                this.historicUserNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Radixx.ConnectPoint.Request")]
    public partial class CarrierCode {
        
        private string accessibleCarrierCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AccessibleCarrierCode {
            get {
                return this.accessibleCarrierCodeField;
            }
            set {
                this.accessibleCarrierCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Radixx.ConnectPoint.Flight.Response")]
    public partial class ViewUpdateLidAircraft {
        
        private bool statusField;
        
        /// <remarks/>
        public bool Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Radixx.ConnectPoint.Flight.Response")]
    public partial class ViewUpdateLidAircraftCollection {
        
        private ViewUpdateLidAircraft[] updateLidAircraftListField;
        
        private ExceptionInformationException[] exceptionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public ViewUpdateLidAircraft[] UpdateLidAircraftList {
            get {
                return this.updateLidAircraftListField;
            }
            set {
                this.updateLidAircraftListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Radixx.ConnectPoint.Exceptions")]
        public ExceptionInformationException[] Exceptions {
            get {
                return this.exceptionsField;
            }
            set {
                this.exceptionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="ExceptionInformation.Exception", Namespace="http://schemas.datacontract.org/2004/07/Radixx.ConnectPoint.Exceptions")]
    public partial class ExceptionInformationException {
        
        private int exceptionCodeField;
        
        private bool exceptionCodeFieldSpecified;
        
        private string exceptionDescriptionField;
        
        private string exceptionSourceField;
        
        private ExceptionLevels exceptionLevelField;
        
        private bool exceptionLevelFieldSpecified;
        
        /// <remarks/>
        public int ExceptionCode {
            get {
                return this.exceptionCodeField;
            }
            set {
                this.exceptionCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExceptionCodeSpecified {
            get {
                return this.exceptionCodeFieldSpecified;
            }
            set {
                this.exceptionCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ExceptionDescription {
            get {
                return this.exceptionDescriptionField;
            }
            set {
                this.exceptionDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ExceptionSource {
            get {
                return this.exceptionSourceField;
            }
            set {
                this.exceptionSourceField = value;
            }
        }
        
        /// <remarks/>
        public ExceptionLevels ExceptionLevel {
            get {
                return this.exceptionLevelField;
            }
            set {
                this.exceptionLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExceptionLevelSpecified {
            get {
                return this.exceptionLevelFieldSpecified;
            }
            set {
                this.exceptionLevelFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Radixx.ConnectPoint.Exceptions")]
    public enum ExceptionLevels {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        Warning,
        
        /// <remarks/>
        Critical,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Radixx.ConnectPoint.Flight.Response")]
    public partial class Route {
        
        private string originAirportCodeField;
        
        private string originAirportDescriptionField;
        
        private string originAirportMetroGroupField;
        
        private string originAirportCurrencyField;
        
        private string destinationAirportCodeField;
        
        private string destinationAirportDescriptionField;
        
        private string destinationAirportMetroGroupField;
        
        private string destinationAirportCurrencyField;
        
        private decimal approximateRouteDurationField;
        
        private bool approximateRouteDurationFieldSpecified;
        
        private bool advPaxInfoCollectionReqField;
        
        private bool advPaxInfoCollectionReqFieldSpecified;
        
        private string originAirportOffsetFromGMTField;
        
        private string originAirportISOCountryCode3Field;
        
        private string destinationAirportISOCountryCode3Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OriginAirportCode {
            get {
                return this.originAirportCodeField;
            }
            set {
                this.originAirportCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OriginAirportDescription {
            get {
                return this.originAirportDescriptionField;
            }
            set {
                this.originAirportDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OriginAirportMetroGroup {
            get {
                return this.originAirportMetroGroupField;
            }
            set {
                this.originAirportMetroGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OriginAirportCurrency {
            get {
                return this.originAirportCurrencyField;
            }
            set {
                this.originAirportCurrencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DestinationAirportCode {
            get {
                return this.destinationAirportCodeField;
            }
            set {
                this.destinationAirportCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DestinationAirportDescription {
            get {
                return this.destinationAirportDescriptionField;
            }
            set {
                this.destinationAirportDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DestinationAirportMetroGroup {
            get {
                return this.destinationAirportMetroGroupField;
            }
            set {
                this.destinationAirportMetroGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DestinationAirportCurrency {
            get {
                return this.destinationAirportCurrencyField;
            }
            set {
                this.destinationAirportCurrencyField = value;
            }
        }
        
        /// <remarks/>
        public decimal ApproximateRouteDuration {
            get {
                return this.approximateRouteDurationField;
            }
            set {
                this.approximateRouteDurationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ApproximateRouteDurationSpecified {
            get {
                return this.approximateRouteDurationFieldSpecified;
            }
            set {
                this.approximateRouteDurationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool AdvPaxInfoCollectionReq {
            get {
                return this.advPaxInfoCollectionReqField;
            }
            set {
                this.advPaxInfoCollectionReqField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AdvPaxInfoCollectionReqSpecified {
            get {
                return this.advPaxInfoCollectionReqFieldSpecified;
            }
            set {
                this.advPaxInfoCollectionReqFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OriginAirportOffsetFromGMT {
            get {
                return this.originAirportOffsetFromGMTField;
            }
            set {
                this.originAirportOffsetFromGMTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OriginAirportISOCountryCode3 {
            get {
                return this.originAirportISOCountryCode3Field;
            }
            set {
                this.originAirportISOCountryCode3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DestinationAirportISOCountryCode3 {
            get {
                return this.destinationAirportISOCountryCode3Field;
            }
            set {
                this.destinationAirportISOCountryCode3Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Radixx.ConnectPoint.Flight.Response")]
    public partial class ViewAirportRoutes {
        
        private Route[] routesField;
        
        private ExceptionInformationException[] exceptionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Route[] Routes {
            get {
                return this.routesField;
            }
            set {
                this.routesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Radixx.ConnectPoint.Exceptions")]
        public ExceptionInformationException[] Exceptions {
            get {
                return this.exceptionsField;
            }
            set {
                this.exceptionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Radixx.ConnectPoint.Flight.Response")]
    public partial class SeatCharge {
        
        private long rowNumberField;
        
        private string seatField;
        
        private string serviceCodeField;
        
        private decimal amountField;
        
        private string currencyField;
        
        /// <remarks/>
        public long RowNumber {
            get {
                return this.rowNumberField;
            }
            set {
                this.rowNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Seat {
            get {
                return this.seatField;
            }
            set {
                this.seatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ServiceCode {
            get {
                return this.serviceCodeField;
            }
            set {
                this.serviceCodeField = value;
            }
        }
        
        /// <remarks/>
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Radixx.ConnectPoint.Flight.Response")]
    public partial class SeatException {
        
        private long rowNumberField;
        
        private string seatField;
        
        private long statusField;
        
        /// <remarks/>
        public long RowNumber {
            get {
                return this.rowNumberField;
            }
            set {
                this.rowNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Seat {
            get {
                return this.seatField;
            }
            set {
                this.seatField = value;
            }
        }
        
        /// <remarks/>
        public long Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Radixx.ConnectPoint.Flight.Response")]
    public partial class SeatAssignment {
        
        private long rowNumberField;
        
        private string seatField;
        
        private long passengerTypeCodeField;
        
        /// <remarks/>
        public long RowNumber {
            get {
                return this.rowNumberField;
            }
            set {
                this.rowNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Seat {
            get {
                return this.seatField;
            }
            set {
                this.seatField = value;
            }
        }
        
        /// <remarks/>
        public long PassengerTypeCode {
            get {
                return this.passengerTypeCodeField;
            }
            set {
                this.passengerTypeCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Radixx.ConnectPoint.Flight.Response")]
    public partial class SeatMap {
        
        private long rowNumberField;
        
        private string seatsField;
        
        private string wingSeatsField;
        
        private string exitSeatsField;
        
        private string blockedSeatsField;
        
        private string preBlockedSeatsField;
        
        /// <remarks/>
        public long RowNumber {
            get {
                return this.rowNumberField;
            }
            set {
                this.rowNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Seats {
            get {
                return this.seatsField;
            }
            set {
                this.seatsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string WingSeats {
            get {
                return this.wingSeatsField;
            }
            set {
                this.wingSeatsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ExitSeats {
            get {
                return this.exitSeatsField;
            }
            set {
                this.exitSeatsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BlockedSeats {
            get {
                return this.blockedSeatsField;
            }
            set {
                this.blockedSeatsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PreBlockedSeats {
            get {
                return this.preBlockedSeatsField;
            }
            set {
                this.preBlockedSeatsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Radixx.ConnectPoint.Flight.Response")]
    public partial class Cabin {
        
        private string cabinNameField;
        
        private SeatMap[] seatMapsField;
        
        private SeatAssignment[] seatAssignmentsField;
        
        private SeatException[] seatExceptionsField;
        
        private SeatCharge[] seatChargesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CabinName {
            get {
                return this.cabinNameField;
            }
            set {
                this.cabinNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public SeatMap[] SeatMaps {
            get {
                return this.seatMapsField;
            }
            set {
                this.seatMapsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public SeatAssignment[] SeatAssignments {
            get {
                return this.seatAssignmentsField;
            }
            set {
                this.seatAssignmentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public SeatException[] SeatExceptions {
            get {
                return this.seatExceptionsField;
            }
            set {
                this.seatExceptionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public SeatCharge[] SeatCharges {
            get {
                return this.seatChargesField;
            }
            set {
                this.seatChargesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Radixx.ConnectPoint.Flight.Response")]
    public partial class SeatCode {
        
        private string serviceCodeField;
        
        private string descriptionField;
        
        private long quantityAvailableField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ServiceCode {
            get {
                return this.serviceCodeField;
            }
            set {
                this.serviceCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public long QuantityAvailable {
            get {
                return this.quantityAvailableField;
            }
            set {
                this.quantityAvailableField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Radixx.ConnectPoint.Flight.Response")]
    public partial class PhysicalFlight {
        
        private int physicalFlightIDField;
        
        private System.DateTime departureDateField;
        
        private string originField;
        
        private string destinationField;
        
        private string originNameField;
        
        private string destinationNameField;
        
        private string tailNumField;
        
        private string flightNumField;
        
        private bool isCircularFlightField;
        
        private int legOrderField;
        
        private bool displayLegOnSeatmapField;
        
        private SeatCode[] seatCodesField;
        
        private Cabin[] cabinsField;
        
        /// <remarks/>
        public int PhysicalFlightID {
            get {
                return this.physicalFlightIDField;
            }
            set {
                this.physicalFlightIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DepartureDate {
            get {
                return this.departureDateField;
            }
            set {
                this.departureDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Origin {
            get {
                return this.originField;
            }
            set {
                this.originField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OriginName {
            get {
                return this.originNameField;
            }
            set {
                this.originNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DestinationName {
            get {
                return this.destinationNameField;
            }
            set {
                this.destinationNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TailNum {
            get {
                return this.tailNumField;
            }
            set {
                this.tailNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FlightNum {
            get {
                return this.flightNumField;
            }
            set {
                this.flightNumField = value;
            }
        }
        
        /// <remarks/>
        public bool IsCircularFlight {
            get {
                return this.isCircularFlightField;
            }
            set {
                this.isCircularFlightField = value;
            }
        }
        
        /// <remarks/>
        public int LegOrder {
            get {
                return this.legOrderField;
            }
            set {
                this.legOrderField = value;
            }
        }
        
        /// <remarks/>
        public bool DisplayLegOnSeatmap {
            get {
                return this.displayLegOnSeatmapField;
            }
            set {
                this.displayLegOnSeatmapField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public SeatCode[] SeatCodes {
            get {
                return this.seatCodesField;
            }
            set {
                this.seatCodesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Cabin[] Cabins {
            get {
                return this.cabinsField;
            }
            set {
                this.cabinsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Radixx.ConnectPoint.Flight.Response")]
    public partial class ViewSeatAvailability {
        
        private PhysicalFlight[] physicalFlightsField;
        
        private ExceptionInformationException[] exceptionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public PhysicalFlight[] PhysicalFlights {
            get {
                return this.physicalFlightsField;
            }
            set {
                this.physicalFlightsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Radixx.ConnectPoint.Exceptions")]
        public ExceptionInformationException[] Exceptions {
            get {
                return this.exceptionsField;
            }
            set {
                this.exceptionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Radixx.ConnectPoint.Flight.Request")]
    public partial class UpdateInventoryAirCraftLid : TransactionInfo {
        
        private string cabinValueField;
        
        private string destinationAirportCodeField;
        
        private System.DateTime flightDateField;
        
        private bool flightDateFieldSpecified;
        
        private string flightNumberField;
        
        private EnumerationsTypeofLid lidTypeField;
        
        private bool lidTypeFieldSpecified;
        
        private int lidValueField;
        
        private bool lidValueFieldSpecified;
        
        private string originAirportCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CabinValue {
            get {
                return this.cabinValueField;
            }
            set {
                this.cabinValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DestinationAirportCode {
            get {
                return this.destinationAirportCodeField;
            }
            set {
                this.destinationAirportCodeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FlightDate {
            get {
                return this.flightDateField;
            }
            set {
                this.flightDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FlightDateSpecified {
            get {
                return this.flightDateFieldSpecified;
            }
            set {
                this.flightDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FlightNumber {
            get {
                return this.flightNumberField;
            }
            set {
                this.flightNumberField = value;
            }
        }
        
        /// <remarks/>
        public EnumerationsTypeofLid LidType {
            get {
                return this.lidTypeField;
            }
            set {
                this.lidTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LidTypeSpecified {
            get {
                return this.lidTypeFieldSpecified;
            }
            set {
                this.lidTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int LidValue {
            get {
                return this.lidValueField;
            }
            set {
                this.lidValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LidValueSpecified {
            get {
                return this.lidValueFieldSpecified;
            }
            set {
                this.lidValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OriginAirportCode {
            get {
                return this.originAirportCodeField;
            }
            set {
                this.originAirportCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Enumerations.TypeofLid", Namespace="http://schemas.datacontract.org/2004/07/Radixx.ConnectPoint.Request")]
    public enum EnumerationsTypeofLid {
        
        /// <remarks/>
        Aircraft,
        
        /// <remarks/>
        Cabin,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Radixx.ConnectPoint.Flight.Request")]
    public partial class RetrieveAirportRoutes : TransactionInfo {
        
        private string languageCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LanguageCode {
            get {
                return this.languageCodeField;
            }
            set {
                this.languageCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void RetrieveSeatAvailabilityListCompletedEventHandler(object sender, RetrieveSeatAvailabilityListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetrieveSeatAvailabilityListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetrieveSeatAvailabilityListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ViewSeatAvailability Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ViewSeatAvailability)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void RetrieveAirportRoutesCompletedEventHandler(object sender, RetrieveAirportRoutesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetrieveAirportRoutesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetrieveAirportRoutesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ViewAirportRoutes Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ViewAirportRoutes)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void UpdateLidAircraftCompletedEventHandler(object sender, UpdateLidAircraftCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateLidAircraftCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateLidAircraftCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ViewUpdateLidAircraftCollection Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ViewUpdateLidAircraftCollection)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591