//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreatePNR_AutomationApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://qa.internalcp.flydubai.comConnectPoint.Flight.svc")]
        public string CreatePNR_AutomationApp_FlightService_ConnectPoint_Flight {
            get {
                return ((string)(this["CreatePNR_AutomationApp_FlightService_ConnectPoint_Flight"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://fzstgtmp.internal.connectpoint.radixx.com/ConnectPoint.Pricing.svc")]
        public string CreatePNR_AutomationApp_PricingService_ConnectPoint_Pricing {
            get {
                return ((string)(this["CreatePNR_AutomationApp_PricingService_ConnectPoint_Pricing"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://qa.internalcp.flydubai.com/ConnectPoint.Security.svc")]
        public string CreatePNR_AutomationApp_SecurityService_ConnectPoint_Security {
            get {
                return ((string)(this["CreatePNR_AutomationApp_SecurityService_ConnectPoint_Security"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://qa.internalcp.flydubai.com/ConnectPoint.Reservation.svc")]
        public string CreatePNR_AutomationApp_ReservationService_ConnectPoint_Reservation {
            get {
                return ((string)(this["CreatePNR_AutomationApp_ReservationService_ConnectPoint_Reservation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://qa.internaltpapi.flydubai.com/RadixxBooking.asmx")]
        public string CreatePNR_AutomationApp_BookingTPAPIService_RadixxBooking {
            get {
                return ((string)(this["CreatePNR_AutomationApp_BookingTPAPIService_RadixxBooking"]));
            }
        }
    }
}
