//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.0.
// 
#pragma warning disable 1591

namespace CreatePNR_AutomationApp.SecurityService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IConnectPoint_Security", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransactionInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CarrierInfo))]
    public partial class ConnectPoint_Security : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RetrieveSecurityTokenOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGroupDataByUseridOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidateSecurityTokenOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ConnectPoint_Security() {
            this.Url = global::CreatePNR_AutomationApp.Properties.Settings.Default.CreatePNR_AutomationApp_SecurityService_ConnectPoint_Security;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RetrieveSecurityTokenCompletedEventHandler RetrieveSecurityTokenCompleted;
        
        /// <remarks/>
        public event GetGroupDataByUseridCompletedEventHandler GetGroupDataByUseridCompleted;
        
        /// <remarks/>
        public event ValidateSecurityTokenCompletedEventHandler ValidateSecurityTokenCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IConnectPoint_Security/RetrieveSecurityToken", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ViewSecurityToken RetrieveSecurityToken([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] RetrieveSecurityToken RetrieveSecurityTokenRequest) {
            object[] results = this.Invoke("RetrieveSecurityToken", new object[] {
                        RetrieveSecurityTokenRequest});
            return ((ViewSecurityToken)(results[0]));
        }
        
        /// <remarks/>
        public void RetrieveSecurityTokenAsync(RetrieveSecurityToken RetrieveSecurityTokenRequest) {
            this.RetrieveSecurityTokenAsync(RetrieveSecurityTokenRequest, null);
        }
        
        /// <remarks/>
        public void RetrieveSecurityTokenAsync(RetrieveSecurityToken RetrieveSecurityTokenRequest, object userState) {
            if ((this.RetrieveSecurityTokenOperationCompleted == null)) {
                this.RetrieveSecurityTokenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetrieveSecurityTokenOperationCompleted);
            }
            this.InvokeAsync("RetrieveSecurityToken", new object[] {
                        RetrieveSecurityTokenRequest}, this.RetrieveSecurityTokenOperationCompleted, userState);
        }
        
        private void OnRetrieveSecurityTokenOperationCompleted(object arg) {
            if ((this.RetrieveSecurityTokenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetrieveSecurityTokenCompleted(this, new RetrieveSecurityTokenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IConnectPoint_Security/GetGroupDataByUserid", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ResponseGetGroupDataByUserid GetGroupDataByUserid([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] RequestGetGroupDataByUserid getGroupDataByUseridRequest) {
            object[] results = this.Invoke("GetGroupDataByUserid", new object[] {
                        getGroupDataByUseridRequest});
            return ((ResponseGetGroupDataByUserid)(results[0]));
        }
        
        /// <remarks/>
        public void GetGroupDataByUseridAsync(RequestGetGroupDataByUserid getGroupDataByUseridRequest) {
            this.GetGroupDataByUseridAsync(getGroupDataByUseridRequest, null);
        }
        
        /// <remarks/>
        public void GetGroupDataByUseridAsync(RequestGetGroupDataByUserid getGroupDataByUseridRequest, object userState) {
            if ((this.GetGroupDataByUseridOperationCompleted == null)) {
                this.GetGroupDataByUseridOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGroupDataByUseridOperationCompleted);
            }
            this.InvokeAsync("GetGroupDataByUserid", new object[] {
                        getGroupDataByUseridRequest}, this.GetGroupDataByUseridOperationCompleted, userState);
        }
        
        private void OnGetGroupDataByUseridOperationCompleted(object arg) {
            if ((this.GetGroupDataByUseridCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGroupDataByUseridCompleted(this, new GetGroupDataByUseridCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IConnectPoint_Security/ValidateSecurityToken", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ViewValidatedSecurityToken ValidateSecurityToken([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ValidateSecurityToken ValidateSecurityTokenRequest) {
            object[] results = this.Invoke("ValidateSecurityToken", new object[] {
                        ValidateSecurityTokenRequest});
            return ((ViewValidatedSecurityToken)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateSecurityTokenAsync(ValidateSecurityToken ValidateSecurityTokenRequest) {
            this.ValidateSecurityTokenAsync(ValidateSecurityTokenRequest, null);
        }
        
        /// <remarks/>
        public void ValidateSecurityTokenAsync(ValidateSecurityToken ValidateSecurityTokenRequest, object userState) {
            if ((this.ValidateSecurityTokenOperationCompleted == null)) {
                this.ValidateSecurityTokenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateSecurityTokenOperationCompleted);
            }
            this.InvokeAsync("ValidateSecurityToken", new object[] {
                        ValidateSecurityTokenRequest}, this.ValidateSecurityTokenOperationCompleted, userState);
        }
        
        private void OnValidateSecurityTokenOperationCompleted(object arg) {
            if ((this.ValidateSecurityTokenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateSecurityTokenCompleted(this, new ValidateSecurityTokenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Radixx.ConnectPoint.Security.Request")]
    public partial class RetrieveSecurityToken : CarrierInfo {
        
        private string logonIDField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LogonID {
            get {
                return this.logonIDField;
            }
            set {
                this.logonIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ValidateSecurityToken))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RetrieveSecurityToken))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Radixx.ConnectPoint.Request")]
    public partial class CarrierInfo {
        
        private CarrierCode[] carrierCodesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public CarrierCode[] CarrierCodes {
            get {
                return this.carrierCodesField;
            }
            set {
                this.carrierCodesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Radixx.ConnectPoint.Request")]
    public partial class CarrierCode {
        
        private string accessibleCarrierCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AccessibleCarrierCode {
            get {
                return this.accessibleCarrierCodeField;
            }
            set {
                this.accessibleCarrierCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Radixx.ConnectPoint.Security.Response")]
    public partial class ViewValidatedSecurityToken {
        
        private ExceptionInformationException[] exceptionsField;
        
        private bool validationResultField;
        
        private bool validationResultFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Radixx.ConnectPoint.Exceptions")]
        public ExceptionInformationException[] Exceptions {
            get {
                return this.exceptionsField;
            }
            set {
                this.exceptionsField = value;
            }
        }
        
        /// <remarks/>
        public bool ValidationResult {
            get {
                return this.validationResultField;
            }
            set {
                this.validationResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValidationResultSpecified {
            get {
                return this.validationResultFieldSpecified;
            }
            set {
                this.validationResultFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="ExceptionInformation.Exception", Namespace="http://schemas.datacontract.org/2004/07/Radixx.ConnectPoint.Exceptions")]
    public partial class ExceptionInformationException {
        
        private int exceptionCodeField;
        
        private bool exceptionCodeFieldSpecified;
        
        private string exceptionDescriptionField;
        
        private string exceptionSourceField;
        
        private ExceptionLevels exceptionLevelField;
        
        private bool exceptionLevelFieldSpecified;
        
        /// <remarks/>
        public int ExceptionCode {
            get {
                return this.exceptionCodeField;
            }
            set {
                this.exceptionCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExceptionCodeSpecified {
            get {
                return this.exceptionCodeFieldSpecified;
            }
            set {
                this.exceptionCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ExceptionDescription {
            get {
                return this.exceptionDescriptionField;
            }
            set {
                this.exceptionDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ExceptionSource {
            get {
                return this.exceptionSourceField;
            }
            set {
                this.exceptionSourceField = value;
            }
        }
        
        /// <remarks/>
        public ExceptionLevels ExceptionLevel {
            get {
                return this.exceptionLevelField;
            }
            set {
                this.exceptionLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExceptionLevelSpecified {
            get {
                return this.exceptionLevelFieldSpecified;
            }
            set {
                this.exceptionLevelFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Radixx.ConnectPoint.Exceptions")]
    public enum ExceptionLevels {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        Warning,
        
        /// <remarks/>
        Critical,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Radixx.ConnectPoint.Security.Response")]
    public partial class GroupDataResChannel {
        
        private EnumerationsReservationChannelTypes resChannelField;
        
        private bool resChannelFieldSpecified;
        
        /// <remarks/>
        public EnumerationsReservationChannelTypes ResChannel {
            get {
                return this.resChannelField;
            }
            set {
                this.resChannelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ResChannelSpecified {
            get {
                return this.resChannelFieldSpecified;
            }
            set {
                this.resChannelFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Enumerations.ReservationChannelTypes", Namespace="http://schemas.datacontract.org/2004/07/Radixx.ConnectPoint.Request")]
    public enum EnumerationsReservationChannelTypes {
        
        /// <remarks/>
        STANDARD,
        
        /// <remarks/>
        WEB,
        
        /// <remarks/>
        GDS,
        
        /// <remarks/>
        TPAPI,
        
        /// <remarks/>
        DCS,
        
        /// <remarks/>
        EXT_WEB,
        
        /// <remarks/>
        PNRIMPORT,
        
        /// <remarks/>
        MOBILE,
        
        /// <remarks/>
        ALL,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Radixx.ConnectPoint.Security.Response")]
    public partial class GroupDataAirport {
        
        private string airportCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AirportCode {
            get {
                return this.airportCodeField;
            }
            set {
                this.airportCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Radixx.ConnectPoint.Security.Response")]
    public partial class GroupData {
        
        private int groupDataIdField;
        
        private bool groupDataIdFieldSpecified;
        
        private string codeField;
        
        private string descriptionField;
        
        private int isActiveField;
        
        private bool isActiveFieldSpecified;
        
        private int useAirportSecurityField;
        
        private bool useAirportSecurityFieldSpecified;
        
        private int useResChannelSecurityField;
        
        private bool useResChannelSecurityFieldSpecified;
        
        private GroupDataAirport[] airportsField;
        
        private GroupDataResChannel[] reservationChannelsField;
        
        /// <remarks/>
        public int GroupDataId {
            get {
                return this.groupDataIdField;
            }
            set {
                this.groupDataIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GroupDataIdSpecified {
            get {
                return this.groupDataIdFieldSpecified;
            }
            set {
                this.groupDataIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public int IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsActiveSpecified {
            get {
                return this.isActiveFieldSpecified;
            }
            set {
                this.isActiveFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int UseAirportSecurity {
            get {
                return this.useAirportSecurityField;
            }
            set {
                this.useAirportSecurityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UseAirportSecuritySpecified {
            get {
                return this.useAirportSecurityFieldSpecified;
            }
            set {
                this.useAirportSecurityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int UseResChannelSecurity {
            get {
                return this.useResChannelSecurityField;
            }
            set {
                this.useResChannelSecurityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UseResChannelSecuritySpecified {
            get {
                return this.useResChannelSecurityFieldSpecified;
            }
            set {
                this.useResChannelSecurityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public GroupDataAirport[] Airports {
            get {
                return this.airportsField;
            }
            set {
                this.airportsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public GroupDataResChannel[] ReservationChannels {
            get {
                return this.reservationChannelsField;
            }
            set {
                this.reservationChannelsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Radixx.ConnectPoint.Security.Response")]
    public partial class ResponseGetGroupDataByUserid {
        
        private GroupData[] groupDatasField;
        
        private ExceptionInformationException[] exceptionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public GroupData[] GroupDatas {
            get {
                return this.groupDatasField;
            }
            set {
                this.groupDatasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Radixx.ConnectPoint.Exceptions")]
        public ExceptionInformationException[] Exceptions {
            get {
                return this.exceptionsField;
            }
            set {
                this.exceptionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RequestGetGroupDataByUserid))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Radixx.ConnectPoint.Request")]
    public partial class TransactionInfo {
        
        private string securityGUIDField;
        
        private CarrierCode[] carrierCodesField;
        
        private string clientIPAddressField;
        
        private string historicUserNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SecurityGUID {
            get {
                return this.securityGUIDField;
            }
            set {
                this.securityGUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public CarrierCode[] CarrierCodes {
            get {
                return this.carrierCodesField;
            }
            set {
                this.carrierCodesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ClientIPAddress {
            get {
                return this.clientIPAddressField;
            }
            set {
                this.clientIPAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string HistoricUserName {
            get {
                return this.historicUserNameField;
            }
            set {
                this.historicUserNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Radixx.ConnectPoint.Security.Request")]
    public partial class RequestGetGroupDataByUserid : TransactionInfo {
        
        private string userIdField;
        
        private int activeOnlyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public int ActiveOnly {
            get {
                return this.activeOnlyField;
            }
            set {
                this.activeOnlyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Radixx.ConnectPoint.Security.Response")]
    public partial class ViewSecurityToken {
        
        private ExceptionInformationException[] exceptionsField;
        
        private string securityTokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Radixx.ConnectPoint.Exceptions")]
        public ExceptionInformationException[] Exceptions {
            get {
                return this.exceptionsField;
            }
            set {
                this.exceptionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SecurityToken {
            get {
                return this.securityTokenField;
            }
            set {
                this.securityTokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Radixx.ConnectPoint.Security.Request")]
    public partial class ValidateSecurityToken : CarrierInfo {
        
        private string securityTokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SecurityToken {
            get {
                return this.securityTokenField;
            }
            set {
                this.securityTokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void RetrieveSecurityTokenCompletedEventHandler(object sender, RetrieveSecurityTokenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetrieveSecurityTokenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetrieveSecurityTokenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ViewSecurityToken Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ViewSecurityToken)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void GetGroupDataByUseridCompletedEventHandler(object sender, GetGroupDataByUseridCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGroupDataByUseridCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGroupDataByUseridCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseGetGroupDataByUserid Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseGetGroupDataByUserid)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void ValidateSecurityTokenCompletedEventHandler(object sender, ValidateSecurityTokenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateSecurityTokenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateSecurityTokenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ViewValidatedSecurityToken Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ViewValidatedSecurityToken)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591